// ── CSV Field Escaping (RFC 4180 compliant) ─────────────────────────
export function escapeCSV(field) {
  if (field === null || field === undefined) return '';
  const str = String(field);
  // Fields containing comma, double quote, newline, or carriage return must be wrapped in double quotes
  if (/[",\n\r]/.test(str)) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
}

// ── Filename Sanitisation ───────────────────────────────────────────
function sanitizeFilename(name) {
  return (name || 'Record')
    .replace(/[^a-zA-Z0-9\s_\-]/g, '')  // remove problematic chars
    .replace(/\s+/g, '_')                // spaces to underscores
    .substring(0, 50);                   // reasonable length
}

// ── CSV Content Generator ───────────────────────────────────────────
export function generateCSV(data) {
  const {
    studentName = 'Student',
    studentId = '',
    university = '',
    semester = '',
    date = new Date().toLocaleDateString(),
    scale = '4.0',
    courses = [],
    gpaResult = {},
  } = data;

  const safeCourses = Array.isArray(courses) ? courses : [];
  const lines = [];

  // Header
  lines.push('NEXA CALCULATOR - ACADEMIC RECORD');
  lines.push('==========================================');
  lines.push('');

  // Student Information
  lines.push('STUDENT INFORMATION');
  lines.push(escapeCSV('Student Name') + ',' + escapeCSV(studentName));
  if (studentId) lines.push(escapeCSV('Student ID') + ',' + escapeCSV(studentId));
  if (university) lines.push(escapeCSV('University') + ',' + escapeCSV(university));
  if (semester) lines.push(escapeCSV('Semester') + ',' + escapeCSV(semester));
  lines.push(escapeCSV('Date') + ',' + escapeCSV(date));
  lines.push(escapeCSV('Scale') + ',' + escapeCSV(scale));
  lines.push('');

  // Course Table
  lines.push('COURSE DETAILS');
  lines.push(
    ['Code', 'Credits', 'Grade', 'Points'].map(escapeCSV).join(',')
  );
  safeCourses.forEach((c) => {
    lines.push(
      [
        escapeCSV(c.code || '—'),
        escapeCSV(c.credits != null ? c.credits : ''),
        escapeCSV(c.grade || '—'),
        escapeCSV(c.points != null ? parseFloat(c.points).toFixed(2) : '0.00'),
      ].join(',')
    );
  });
  lines.push('');

  // Academic Summary
  lines.push('ACADEMIC SUMMARY');
  lines.push(escapeCSV('GPA') + ',' + escapeCSV(gpaResult?.gpa || ''));
  lines.push(escapeCSV('Total Credits') + ',' + escapeCSV(gpaResult?.credits || ''));
  const points = gpaResult?.points != null ? parseFloat(gpaResult.points).toFixed(2) : '0.00';
  lines.push(escapeCSV('Quality Points') + ',' + escapeCSV(points));
  lines.push('');

  // Footer
  lines.push('Generated by Nexa Calculator - Crafted by Usman Murtaza');
  lines.push('nexacalculator.netlify.app');

  // Prepend BOM for UTF-8 compatibility with MS Excel
  return '\uFEFF' + lines.join('\n');
}

// ── Download Trigger ────────────────────────────────────────────────
export function downloadCSV(data) {
  try {
    const csv = generateCSV(data);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `Nexa_Record_${sanitizeFilename(data.studentName)}.csv`;
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    // Clean up after a short delay to allow download to start
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  } catch (err) {
    console.error('CSV export failed:', err);
    throw new Error('Could not generate CSV file.');
  }
}