export function escapeCSV(field) {
  if (field === null || field === undefined) return '';
  const str = String(field);
  if (/[",\n\r]/.test(str)) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
}

export function generateCSV(data) {
  const safeCourses = Array.isArray(data.courses) ? data.courses : [];
  const lines = [];
  lines.push('NEXA CALCULATOR - ACADEMIC RECORD');
  lines.push('==========================================');
  lines.push('');
  lines.push('STUDENT INFORMATION');
  lines.push(['Student Name', data.studentName].map(escapeCSV).join(','));
  lines.push(['Student ID', data.studentId || ''].map(escapeCSV).join(','));
  lines.push(['University', data.university || ''].map(escapeCSV).join(','));
  lines.push(['Semester', data.semester || ''].map(escapeCSV).join(','));
  lines.push(['Date', data.date].map(escapeCSV).join(','));
  lines.push(['Scale', data.scale].map(escapeCSV).join(','));
  lines.push('');
  lines.push('COURSE DETAILS');
  lines.push(['Code', 'Credits', 'Grade', 'Points'].map(escapeCSV).join(','));
  safeCourses.forEach((c) =>
    lines.push([c.code || '—', c.credits, c.grade, c.points].map(escapeCSV).join(','))
  );
  lines.push('');
  lines.push('ACADEMIC SUMMARY');
  lines.push(['GPA', data.gpaResult?.gpa || ''].map(escapeCSV).join(','));
  lines.push(['Credits', data.gpaResult?.credits || ''].map(escapeCSV).join(','));
  lines.push(['Points', (data.gpaResult?.points || 0).toFixed(2)].map(escapeCSV).join(','));
  lines.push('');
  lines.push('Generated by Nexa Calculator - Crafted by Usman Murtaza');

  return '\uFEFF' + lines.join('\n');
}

export function downloadCSV(data) {
  const csv = generateCSV(data);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Nexa_Record_${data.studentName.replace(/\s+/g, '_')}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}