import { SCALES, GRADES_4 } from "../constants/grades";

// ── Standing ──────────────────────────────────────────────────────────────────
export function getStanding(gpa, scale = "4.0") {
  const max = parseFloat(scale);
  const pct = (gpa / max) * 100;
  if (pct >= 92.5) return { t: "Outstanding — Dean's List", color: "#a78bfa" };
  if (pct >= 75)   return { t: "Very Good Standing",        color: "#34d399" };
  if (pct >= 62.5) return { t: "Good Standing",             color: "#60a5fa" };
  if (pct >= 50)   return { t: "Satisfactory",              color: "#fbbf24" };
  if (pct >= 25)   return { t: "Below Average",             color: "#f87171" };
  return               { t: "Academic Probation",        color: "#ef4444" };
}

// ── GPA Calculation ───────────────────────────────────────────────────────────
export function calcGPA(courses, scale) {
  const gradeScale = SCALES[scale] ?? GRADES_4;
  let totalPoints = 0;
  let totalCredits = 0;
  for (const c of courses) {
    const grade = gradeScale[c.gradeIdx];
    if (!grade) continue;
    totalPoints  += grade.p * c.credits;
    totalCredits += c.credits;
  }
  const gpa = totalCredits > 0 ? totalPoints / totalCredits : 0;
  return {
    gpa:     parseFloat(gpa.toFixed(2)),
    count:   courses.length,
    credits: totalCredits,
    points:  totalPoints,
  };
}

// ── CGPA Calculation ──────────────────────────────────────────────────────────
export function calcCGPA(sems, scale) {
  const max = parseFloat(scale);
  let total = 0, count = 0, best = 0;
  for (const s of sems) {
    if (s.val === "" || s.val === null) continue;
    const n = parseFloat(s.val);
    if (isNaN(n) || n < 0 || n > max) {
      return { error: `Enter valid GPA values (0.00 – ${max.toFixed(2)}).` };
    }
    total += n;
    count++;
    if (n > best) best = n;
  }
  if (!count) return { error: "Please enter at least one semester GPA." };
  return {
    cgpa:  parseFloat((total / count).toFixed(2)),
    sems:  count,
    total: parseFloat(total.toFixed(2)),
    best:  parseFloat(best.toFixed(2)),
  };
}

// ── CSV Export ────────────────────────────────────────────────────────────────
const csvCell = (v) => {
  const str = String(v ?? "");
  return str.includes(",") || str.includes('"') || str.includes("\n")
    ? `"${str.replace(/"/g, '""')}"` : str;
};

export function exportCSV(data) {
  const { studentName, studentId, university, semester, date, scale, courses, gpaResult } = data;
  const rows = [
    ["NEXA CALCULATOR - ACADEMIC RECORD"],
    ["=========================================="],
    [],
    ["STUDENT INFORMATION"],
    ["Student Name", csvCell(studentName)],
    ["Student ID",   csvCell(studentId)],
    ["University",   csvCell(university)],
    ["Semester",     csvCell(semester)],
    ["Date",         csvCell(date)],
    ["Scale",        csvCell(scale)],
    [],
    ["COURSE DETAILS"],
    ["Code", "Credits", "Grade", "Points"],
    ...courses.map(c => [csvCell(c.code), c.credits, csvCell(c.grade), c.points]),
    [],
    ["ACADEMIC SUMMARY"],
    ["GPA",     gpaResult.gpa],
    ["Credits", gpaResult.credits],
    ["Points",  parseFloat(gpaResult.points).toFixed(2)],
    [],
    ["Generated by Nexa Calculator - Crafted by Usman Murtaza"],
  ];

  const csv = rows.map(r => r.join(",")).join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `Nexa_Record_${studentName.replace(/\s+/g, "_")}.csv`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

// ── PDF Export ────────────────────────────────────────────────────────────────
export function exportPDF(doc, data) {
  const { studentName, studentId, university, semester, date, scale, courses, gpaResult } = data;

  // Header band
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, 210, 40, "F");
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("NEXA CALCULATOR", 105, 25, { align: "center" });
  doc.setFontSize(12);
  doc.setTextColor(199, 181, 253);
  doc.text("Academic Excellence Suite", 105, 35, { align: "center" });

  let y = 55;

  // Section heading
  doc.setDrawColor(124, 58, 237);
  doc.line(15, y - 5, 195, y - 5);
  doc.setFontSize(16);
  doc.setTextColor(124, 58, 237);
  doc.text("ACADEMIC RECORD", 105, y, { align: "center" });
  y += 12;

  // Student info
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "bold");
  doc.text("Student Information", 20, y); y += 8;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(`Name: ${studentName}`, 25, y); y += 6;
  if (studentId)  { doc.text(`Student ID: ${studentId}`,     25, y); y += 6; }
  if (university) { doc.text(`Institution: ${university}`,   25, y); y += 6; }
  if (semester)   { doc.text(`Semester: ${semester}`,        25, y); y += 6; }
  doc.text(`Generated: ${date}`, 25, y); y += 12;

  // Course table
  doc.line(20, y, 190, y); y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(124, 58, 237);
  doc.text("Course Details", 20, y); y += 8;

  doc.setFillColor(124, 58, 237);
  doc.rect(20, y, 170, 8, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("Course Code", 25, y + 5.5);
  doc.text("Credits",     85, y + 5.5);
  doc.text("Grade",      115, y + 5.5);
  doc.text("Points",     155, y + 5.5);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  courses.forEach((c, i) => {
    if (y > 250) { doc.addPage(); y = 20; }
    if (i % 2 === 0) { doc.setFillColor(245, 245, 250); doc.rect(20, y - 4, 170, 7, "F"); }
    doc.text(c.code,            25, y);
    doc.text(String(c.credits), 85, y);
    doc.text(c.grade,          115, y);
    doc.text(c.points,         155, y);
    y += 7;
  });

  // Summary
  y += 10;
  doc.setDrawColor(124, 58, 237);
  doc.line(20, y, 190, y); y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(124, 58, 237);
  doc.text("Academic Summary", 20, y); y += 10;

  doc.setFillColor(249, 248, 255);
  doc.rect(20, y - 4, 170, 30, "F");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "bold");
  doc.text("GPA", 40, y + 3);
  doc.setFontSize(18);
  doc.setTextColor(124, 58, 237);
  doc.text(String(gpaResult.gpa), 40, y + 15);
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`out of ${scale}`, 40, y + 22);
  doc.setFont("helvetica", "bold");
  doc.text("Total Credits", 105, y + 3);
  doc.setFontSize(14);
  doc.setTextColor(80, 80, 80);
  doc.text(String(gpaResult.credits), 105, y + 15);
  doc.setFont("helvetica", "bold");
  doc.text("Quality Points", 150, y + 3);
  doc.setFontSize(14);
  doc.text(parseFloat(gpaResult.points).toFixed(2), 150, y + 15);
  y += 40;

  // Standing banner
  const standing = getStanding(parseFloat(gpaResult.gpa), scale);
  const hexToRgb = (hex) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b];
  };
  const [r, g, b] = hexToRgb(standing.color);
  doc.setFillColor(r, g, b);
  doc.rect(20, y - 4, 170, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text(`Academic Standing: ${standing.t}`, 105, y + 3, { align: "center" });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: "center" });
    doc.setFontSize(10);
    doc.setTextColor(124, 58, 237);
    doc.text("Crafted by Usman Murtaza • Nexa Calculator", 105, 290, { align: "center" });
    doc.text("nexacalculator.netlify.app", 105, 295, { align: "center" });
  }

  doc.save(`Nexa_Academic_Record_${studentName.replace(/\s+/g, "_")}.pdf`);
}

// ── Email validation ──────────────────────────────────────────────────────────
export const isValidEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());